import { test, expect } from './helpers/test.mjs'
import { setup, tap, armed } from './helpers/controller.mjs'

test('developer toggles pause simulation, reveal the map, publish credits and jump through shared prerequisites',async({page})=>{
  await page.goto('/hard-vacuum')
  await page.getByRole('button',{name:'Launch expedition',exact:true}).press('Enter')
  await page.keyboard.press('Backquote')
  const panel=page.getByRole('dialog',{name:'Developer panel',exact:true})
  await expect(panel).toBeVisible()
  await panel.getByRole('button',{name:'Add 100,000 banked credits',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('100,000')
  await panel.getByRole('button',{name:'Show whole map',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Station survey',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Local survey · O',exact:true})).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.hud-credits')).toContainText('100,000')
  await page.keyboard.press('Backquote')
  await panel.getByRole('button',{name:/3\.The Works|3\. The Works/}).click()
  await expect(panel).toHaveCount(0)
  await expect(page.locator('.hud-room')).toContainText('The Works')
  await expect(page.getByRole('button',{name:/Fire blaster/})).toHaveCount(0)
  await page.keyboard.press('Backquote')
  await expect(panel.getByRole('button',{name:'Show whole map',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.keyboard.press('Escape')
  await expect(page.locator('canvas')).toBeFocused()
})

test('controller targets the visible developer dialog above a map and respects grid columns',async({page})=>{
  await setup(page,armed());await tap(page,0);await tap(page,8)
  await page.keyboard.press('Backquote');await page.clock.runFor(64)
  const panel=page.getByRole('dialog',{name:'Developer panel',exact:true})
  await expect(panel).toBeVisible()
  await tap(page,13)
  await expect(panel.getByRole('button',{name:/3\.The Works|3\. The Works/})).toBeFocused()
  await tap(page,1)
  await expect(panel).toHaveCount(0)
  await expect(page.getByRole('dialog',{name:'Station survey',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Station overview · Y / △',exact:true})).toBeFocused()
  await tap(page,1)
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('Tab follows grid reading order while arrows follow its columns and Escape restores the map', async ({ page }) => {
  await setup(page, armed()); await tap(page, 0); await tap(page, 8)
  await page.keyboard.press('Backquote')
  const panel = page.getByRole('dialog', { name: 'Developer panel', exact: true })
  const levels = panel.locator('[data-menu-grid] button')
  await page.keyboard.press('Home'); await expect(levels.nth(0)).toBeFocused()
  await page.keyboard.press('Tab'); await expect(levels.nth(1)).toBeFocused()
  await page.keyboard.press('Tab'); await expect(levels.nth(2)).toBeFocused()
  await page.keyboard.press('Shift+Tab'); await expect(levels.nth(1)).toBeFocused()
  await page.keyboard.press('ArrowDown'); await expect(levels.nth(3)).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Station overview · Y / △', exact: true })).toBeFocused()
})
