import { test, expect } from '@playwright/test'
import { setup, tap, armed } from './helpers/controller.mjs'

test('developer toggles pause simulation, reveal the map, publish credits and jump through shared prerequisites',async({page})=>{
  await page.goto('/hard-vacuum')
  await page.getByRole('button',{name:'Launch expedition',exact:true}).press('Enter')
  await page.keyboard.press('Backquote')
  const panel=page.getByRole('dialog',{name:'Developer panel',exact:true})
  await expect(panel).toBeVisible()
  await panel.getByRole('button',{name:'Add 100,000 banked credits',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('100,000')
  await panel.getByRole('button',{name:'Show whole map',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Station survey',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Local survey · O',exact:true})).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.hud-credits')).toContainText('100,000')
  await page.keyboard.press('Backquote')
  await panel.getByRole('button',{name:/3\.The Works|3\. The Works/}).click()
  await expect(panel).toHaveCount(0)
  await expect(page.locator('.hud-room')).toContainText('The Works')
  await expect(page.getByRole('button',{name:/Fire blaster/})).toHaveCount(0)
  await page.keyboard.press('Backquote')
  await expect(panel.getByRole('button',{name:'Show whole map',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.keyboard.press('Escape')
  await expect(page.locator('canvas')).toBeFocused()
})

test('controller targets the visible developer dialog above a map and respects grid columns',async({page})=>{
  await setup(page,armed());await tap(page,0);await tap(page,8)
  await page.keyboard.press('Backquote');await page.clock.runFor(64)
  const panel=page.getByRole('dialog',{name:'Developer panel',exact:true})
  await expect(panel).toBeVisible()
  await tap(page,13)
  await expect(panel.getByRole('button',{name:/3\.The Works|3\. The Works/})).toBeFocused()
  await tap(page,1)
  await expect(panel).toHaveCount(0)
  await expect(page.getByRole('dialog',{name:'Station survey',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Station overview · O',exact:true})).toBeFocused()
  await tap(page,1)
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
