import { test, expect } from './helpers/test.mjs'

async function open(page) {
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') })
  await page.addInitScript(() => {
    const proto = CanvasRenderingContext2D.prototype, rect = proto.fillRect, ellipse = proto.ellipse
    proto.fillRect = function (...args) {
      if (args[0] === 0 && args[1] === 920 && args[2] >= 800) window.jumpCamera = this.getTransform()
      return rect.apply(this, args)
    }
    proto.ellipse = function (...args) {
      if (args[2] === 6.2 && args[3] === 6.2 && window.jumpCamera) {
        const body = this.getTransform(), camera = window.jumpCamera
        window.jumpPlayer = { x: (body.e - camera.e) / camera.a, y: (body.f - camera.f) / camera.d }
      }
      return ellipse.apply(this, args)
    }
  })
  await page.goto('/untitled-jumping-game')
  await page.getByRole('button', { name: 'Level builder', exact: true }).click()
  await expect(page.getByRole('application', { name: 'Level canvas' })).toBeVisible()
  await page.clock.pauseAt(new Date('2026-01-01T01:00:00Z'))
  await page.clock.runFor(64)
}
async function dragWorld(page, start, end) {
  const canvas = await page.getByRole('application', { name: 'Level canvas' }).boundingBox()
  const camera = await page.evaluate(() => { const c = window.jumpCamera; return { a: c.a, d: c.d, e: c.e, f: c.f, ratio: devicePixelRatio } })
  const x = v => canvas.x + (v * camera.a + camera.e) / camera.ratio, y = v => canvas.y + (v * camera.d + camera.f) / camera.ratio
  await page.mouse.move(x(start.x), y(start.y)); await page.mouse.down()
  await page.mouse.move(x(end.x), y(end.y), { steps: 8 }); await page.mouse.up()
}

test('build, edit, undo, save, playtest, return and reload a custom level', async ({ page }, info) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await open(page)
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'New level', exact: true }).click()
  await page.getByRole('textbox', { name: 'Level name' }).fill('Slope workshop')
  await page.getByRole('button', { name: 'Ramp', exact: true }).click()
  await dragWorld(page, { x: 360, y: 920 }, { x: 660, y: 800 })
  await expect(page.getByRole('spinbutton', { name: 'Object w', exact: true })).toHaveValue('300')
  await expect(page.getByRole('spinbutton', { name: 'Object h', exact: true })).toHaveValue('120')
  await page.getByRole('spinbutton', { name: 'Object w', exact: true }).fill('400')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('combobox', { name: 'Selected object' }).selectOption('platform:0')
  await expect(page.getByRole('spinbutton', { name: 'Object w', exact: true })).toHaveValue('300')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await page.getByRole('combobox', { name: 'Selected object' }).selectOption('platform:0')
  await expect(page.getByRole('spinbutton', { name: 'Object w', exact: true })).toHaveValue('400')
  await page.getByRole('button', { name: 'Save level', exact: true }).click()
  await expect(page.getByRole('status', { name: 'Builder status' })).toContainText('Saved “Slope workshop”')
  await page.clock.runFor(600)
  await page.screenshot({ path: info.outputPath('level-builder.png') })
  await page.getByRole('button', { name: 'Playtest', exact: false }).click()
  await page.clock.runFor(100)
  await expect(page.locator('canvas[aria-label="Slope workshop: reach the flag"]')).toBeFocused()
  await page.keyboard.down('d'); await page.clock.runFor(1100); await page.keyboard.up('d'); await page.clock.runFor(100)
  const p = await page.evaluate(() => window.jumpPlayer)
  expect(p.x).toBeGreaterThan(450); expect(p.y).toBeLessThan(900)
  await page.screenshot({ path: info.outputPath('custom-level-playtest.png') })
  await page.getByRole('button', { name: 'Return to builder' }).click()
  await expect(page.getByRole('textbox', { name: 'Level name' })).toHaveValue('Slope workshop')
  await expect(page.getByRole('spinbutton', { name: 'Object w', exact: true })).toHaveValue('400')
  // Let React's lazy-route scheduling run normally across the reload.
  await page.clock.resume(); await page.reload()
  await page.getByRole('button', { name: 'Level builder', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Level name' })).toHaveValue('Slope workshop')
  const levels = await page.evaluate(() => JSON.parse(localStorage.getItem('arcade.jumping.levels.v1')))
  expect(levels).toHaveLength(1); expect(levels[0].platforms).toHaveLength(1)
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'New level', exact: true }).click()
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('combobox', { name: 'Saved levels' }).selectOption({ label: 'Slope workshop' })
  await page.getByRole('button', { name: 'Load level', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Level name' })).toHaveValue('Slope workshop')
  expect(errors).toEqual([])
})

test('rough terrain can be reshaped and removed, with undo restoring it', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'New level', exact: true }).click()
  await page.getByRole('button', { name: 'Rough terrain', exact: true }).click()
  await dragWorld(page, { x: 340, y: 920 }, { x: 800, y: 800 })
  await dragWorld(page, { x: 340 + 460 * .4, y: 800 + 120 * .5 }, { x: 340 + 460 * .4, y: 800 + 120 * .5 - 40 })
  await page.clock.runFor(600)
  const draft = await page.evaluate(() => JSON.parse(localStorage.getItem('arcade.jumping.draft.v1')))
  expect(draft.platforms[0].profile[4][1]).toBe(20)
  await page.getByRole('button', { name: 'Delete object' }).click()
  await expect(page.getByRole('combobox', { name: 'Selected object' }).locator('option')).toHaveCount(3)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Selected object' }).locator('option')).toHaveCount(4)
})

test('exported levels import successfully and bad imports leave the current draft intact', async ({ page }) => {
  await open(page)
  await page.getByRole('textbox', { name: 'Level name' }).fill('Export me')
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export', exact: true }).click()])
  expect(download.suggestedFilename()).toBe('Export me.jump-level.json')
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'New level', exact: true }).click()
  await page.getByLabel('Import level file').setInputFiles(await download.path())
  await expect(page.getByRole('textbox', { name: 'Level name' })).toHaveValue('Export me')
  await expect(page.getByRole('status', { name: 'Builder status' })).toContainText('Imported')
  await page.getByLabel('Import level file').setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{"version":1,"platforms":[]}') })
  await expect(page.getByRole('status', { name: 'Builder status' })).toContainText('Could not import')
  await expect(page.getByRole('textbox', { name: 'Level name' })).toHaveValue('Export me')
})

test('storage failures are visible and do not falsely report a successful save', async ({ page }) => {
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new Error('Storage full') } })
  await open(page)
  await page.getByRole('button', { name: 'Save level', exact: true }).click()
  await expect(page.getByRole('status', { name: 'Builder status' })).toContainText('Could not save')
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Saved levels' }).locator('option')).toHaveCount(1)
})

test('builder controls and drawing area remain usable on a narrow screen', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 }); await open(page)
  await expect(page.getByRole('button', { name: 'Playtest' })).toBeInViewport()
  const box = await page.getByRole('application', { name: 'Level canvas' }).boundingBox()
  expect(box.width).toBeGreaterThan(200); expect(box.height).toBeGreaterThan(130)
  expect(await page.locator('.jumping-builder').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('level-builder-mobile.png') })
})

test('author a complete rope trial with props, a pusher, linked machinery, and portable export', async ({ page }, info) => {
  test.setTimeout(90000)
  await open(page)
  await page.screenshot({ path: info.outputPath('level-studio-overview.png') })
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: /Hand Over Hand/ }).click()
  await page.getByRole('textbox', { name: 'Level name' }).fill('My rope course')
  await page.getByLabel('Jump guide', { exact: true }).check()
  for (const [name, x] of [['Crate', '850'], ['Ball', '680'], ['Pusher', '1040'], ['Elevator', '1190'], ['Gate', '1390'], ['Pressure plate', '730']]) {
    await page.getByRole('button', { name, exact: true }).click()
    await page.getByRole('button', { name: 'Add at view center' }).click()
    await page.getByRole('spinbutton', { name: 'Object x', exact: true }).fill(x)
  }
  await page.getByRole('combobox', { name: 'Connected mechanism' }).selectOption({ label: 'Elevator 1' })
  await page.getByRole('combobox', { name: 'Pressure mode' }).selectOption('touch')
  await page.getByRole('button', { name: 'Save level', exact: true }).click()
  await expect(page.getByRole('status', { name: 'Builder status' })).toContainText('Saved')
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export', exact: true }).click()])
  expect(download.suggestedFilename()).toBe('My rope course.jump-level.json')
  const { readFile } = await import('node:fs/promises')
  const exported = JSON.parse(await readFile(await download.path(), 'utf8'))
  expect(exported.climbables.ropes).toHaveLength(2); expect(exported.props).toHaveLength(2)
  expect(exported.robots).toHaveLength(1); expect(exported.mechanisms).toHaveLength(2)
  expect(exported.triggers[0].target).toBe(exported.mechanisms[0].id); expect(exported.triggers[0].mode).toBe('touch')
  expect(exported.flag.x).toBe(1730); expect(exported.times.gold).toBe(11)
  await page.getByRole('combobox', { name: 'Selected object' }).selectOption('prop:0')
  await page.getByRole('button', { name: 'Duplicate', exact: true }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('combobox', { name: 'Selected object' }).selectOption('mechanism:0')
  await page.getByRole('button', { name: 'Delete object' }).click()
  await expect(page.getByRole('button', { name: 'Playtest' })).toBeDisabled()
  await expect(page.getByRole('alert')).toContainText('Connect each pressure plate')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('combobox', { name: 'Selected object' }).selectOption('trigger:0')
  await page.screenshot({ path: info.outputPath('level-studio-connections.png') })
  await page.getByRole('button', { name: 'Playtest' }).click(); await page.clock.runFor(100)
  await expect(page.getByRole('img', { name: 'My rope course: reach the flag' })).toBeFocused()
  await page.keyboard.down('d'); await page.clock.runFor(400); await page.keyboard.up('d')
  await page.keyboard.press('r'); await page.clock.runFor(100)
  await expect(page.getByTestId('level-time')).toHaveText('0:00.00')
  await expect(page.getByRole('img', { name: 'My rope course: reach the flag' })).toBeVisible()
  await page.getByRole('button', { name: 'Return to builder' }).click()
  await expect(page.getByRole('textbox', { name: 'Level name' })).toHaveValue('My rope course')
  await page.getByLabel('Import level file').setInputFiles(await download.path())
  await page.getByRole('button', { name: 'Save level', exact: true }).click()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('arcade.jumping.levels.v1')).at(-1))
  expect(saved.id).not.toBe(exported.id); expect(saved.props).toEqual(exported.props); expect(saved.mechanisms).toEqual(exported.mechanisms)
  expect(saved.triggers).toEqual(exported.triggers)
})
