import { test, expect } from './helpers/folderTest.mjs'
import { selectBuilderObject, selectBuilderOption, installTestFolder, useLevelFixtures, saveTestLevel, reopenTestLevel } from './helpers/jumpingLevels.mjs'
import { readLevelAsset } from '../helpers/jumping-fixtures.mjs'

async function openSwitches(page) {
  const level = readLevelAsset('switch-modes.json')
  level.triggers[0].w = 100
  await useLevelFixtures(page, [level]); await installTestFolder(page, { 'switches.json': level })
  await page.goto('/untitled-jumping-game')
  await page.getByRole('button', { name: 'Level studio', exact: true }).click()
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  const local = page.getByRole('dialog').getByRole('button', { name: 'Local folder', exact: true })
  if (await local.count()) await local.click()
  await page.getByRole('button', { name: 'Choose folder', exact: true }).click()
  await page.getByRole('button', { name: 'Open switches.json', exact: true }).click()
  await expect(page.getByRole('application', { name: 'Level canvas' })).toHaveAttribute('aria-busy', 'false')
}

test('dedicated logic nodes wire, undo, duplicate and reopen without Power or Relay controls', async ({ page }, info) => {
  await openSwitches(page)
  const canvas = page.getByRole('application', { name: 'Level canvas' })
  await page.getByRole('button', { name: 'Logic relay', exact: true }).click()
  const bounds = await canvas.boundingBox()
  await canvas.click({ position: { x: bounds.width * .45, y: bounds.height * .35 } })
  await selectBuilderObject(page, 'logic-relay:0')
  await expect(page.getByRole('heading', { name: 'Logic relay 1', exact: true })).toBeVisible()
  const behavior = page.getByRole('group', { name: 'Switch behavior', exact: true })
  await expect(behavior.getByRole('checkbox', { name: 'Relay', exact: true })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: /power/i })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Switch logic', exact: true })).toHaveText('OR')
  await selectBuilderOption(page, 'Switch logic', 'xor')
  await behavior.getByRole('checkbox', { name: 'Reversed', exact: true }).check()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await selectBuilderObject(page, 'logic-relay:0')
  await expect(behavior.getByRole('checkbox', { name: 'Reversed', exact: true })).not.toBeChecked()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await selectBuilderObject(page, 'logic-relay:0')
  await expect(behavior.getByRole('checkbox', { name: 'Reversed', exact: true })).toBeChecked()
  await page.getByRole('group', { name: 'Switched by', exact: true }).getByRole('checkbox', { name: 'Pressure plate 1', exact: true }).check()
  await page.getByRole('group', { name: 'Activates', exact: true }).getByRole('checkbox', { name: 'Spotlight 1', exact: true }).check()
  await behavior.scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('logic-relay-inspector.png') })
  await selectBuilderObject(page, 'light:0')
  await expect(page.getByRole('group', { name: 'Switched by', exact: true }).getByRole('checkbox', { name: 'Logic relay 1', exact: true })).toBeChecked()
  await selectBuilderObject(page, 'logic-relay:0')
  await page.getByRole('button', { name: 'Duplicate', exact: true }).click()
  const saved = await saveTestLevel(page)
  expect(saved.level.logicRelays).toHaveLength(2)
  for (const relay of saved.level.logicRelays) {
    expect(relay).toMatchObject({ switchLogic: 'xor', switchReversed: true, targets: ['lamp'] })
    expect(relay.power).toBeUndefined(); expect(relay.relay).toBeUndefined()
  }
  expect(saved.level.logicRelays[0].id).not.toBe(saved.level.logicRelays[1].id)
  expect(saved.level.triggers[0].targets).toContain(saved.level.logicRelays[0].id)
  await page.reload(); await reopenTestLevel(page, saved)
  await selectBuilderObject(page, 'logic-relay:0')
  await expect(page.getByRole('combobox', { name: 'Switch logic', exact: true })).toHaveText('XOR')
  await expect(behavior.getByRole('checkbox', { name: 'Reversed', exact: true })).toBeChecked()
  await expect(page.getByRole('group', { name: 'Activates', exact: true }).getByRole('checkbox', { name: 'Spotlight 1', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Delete object', exact: true }).click()
  await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('group', { name: 'Activates', exact: true }).getByRole('checkbox', { name: 'Logic relay 1', exact: true })).not.toBeChecked()
  const deleted = await saveTestLevel(page)
  expect(deleted.level.triggers[0].targets).not.toContain(saved.level.logicRelays[0].id)
})

test('Wall light places, switches, relays, duplicates and reopens with its saved settings', async ({ page }, info) => {
  await openSwitches(page)
  const canvas = page.getByRole('application', { name: 'Level canvas' })
  await page.getByRole('button', { name: 'Wall light', exact: true }).click()
  const bounds = await canvas.boundingBox()
  await canvas.click({ position: { x: bounds.width * .45, y: bounds.height * .35 } })
  await selectBuilderObject(page, 'wall-light:0')
  await expect(page.getByRole('heading', { name: 'Wall light 1', exact: true })).toBeVisible()
  const behavior = page.getByRole('group', { name: 'Switch behavior', exact: true })
  await expect(page.getByRole('combobox', { name: /power/i })).toHaveCount(0)
  await expect(behavior.getByRole('checkbox', { name: 'Relay', exact: true })).not.toBeChecked()
  await page.getByRole('group', { name: 'Switched by', exact: true }).getByRole('checkbox', { name: 'Pressure plate 1', exact: true }).check()
  await selectBuilderOption(page, 'Switch logic', 'xor')
  await behavior.getByRole('checkbox', { name: 'Reversed', exact: true }).check()
  await behavior.getByRole('checkbox', { name: 'Relay', exact: true }).check()
  await page.getByRole('group', { name: 'Activates', exact: true }).getByRole('checkbox', { name: 'Gate 3', exact: true }).check()
  await behavior.scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('wall-light-inspector.png') })
  await page.getByRole('button', { name: 'Duplicate', exact: true }).click()
  const saved = await saveTestLevel(page)
  expect(saved.level.wallLights).toHaveLength(2)
  expect(saved.level.wallLights[0]).toMatchObject({ switchLogic: 'xor', switchReversed: true, relay: true, targets: ['gate'] })
  expect(saved.level.wallLights[1]).toMatchObject({ switchLogic: 'xor', switchReversed: true, relay: true, targets: ['gate'] })
  expect(saved.level.wallLights[0].id).not.toBe(saved.level.wallLights[1].id)
  expect(saved.level.triggers[0].targets).toContain(saved.level.wallLights[0].id)
  await page.reload(); await reopenTestLevel(page, saved)
  await selectBuilderObject(page, 'wall-light:0')
  await expect(page.getByRole('combobox', { name: 'Switch logic', exact: true })).toHaveText('XOR')
  await expect(behavior.getByRole('checkbox', { name: 'Reversed', exact: true })).toBeChecked()
  await expect(behavior.getByRole('checkbox', { name: 'Relay', exact: true })).toBeChecked()
})

test('logic, reversal, opt-in relays and plate mounts save, undo, reopen and flag feedback loops', async ({ page }, info) => {
  await openSwitches(page)
  const behavior = page.getByRole('group', { name: 'Switch behavior', exact: true })
  const incoming = page.getByRole('group', { name: 'Switched by', exact: true })
  const outgoing = page.getByRole('group', { name: 'Activates', exact: true })
  const objects = [['mechanism:0', 'and'], ['mechanism:1', 'xor'], ['mechanism:2', 'or'], ['goal:0', 'and'], ['light:0', 'xor']]
  for (const [object, logic] of objects) {
    await selectBuilderObject(page, object)
    await expect(page.getByRole('combobox', { name: 'Switch logic', exact: true })).toHaveText('OR')
    await expect(behavior.getByRole('checkbox', { name: 'Reversed', exact: true })).not.toBeChecked()
    await expect(behavior.getByRole('checkbox', { name: 'Relay', exact: true })).not.toBeChecked()
    await expect(incoming.getByRole('checkbox')).toHaveCount(1)
    await expect(outgoing).toHaveCount(0)
    await selectBuilderOption(page, 'Switch logic', logic)
    await behavior.getByRole('checkbox', { name: 'Reversed', exact: true }).check()
  }
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await selectBuilderObject(page, 'light:0')
  await expect(behavior.getByRole('checkbox', { name: 'Reversed', exact: true })).not.toBeChecked()
  await page.getByRole('button', { name: 'Redo', exact: true }).click(); await selectBuilderObject(page, 'light:0')
  await expect(behavior).toContainText('Off when exactly one connected switch is active. On otherwise.')
  await selectBuilderObject(page, 'mechanism:0')
  await behavior.getByRole('checkbox', { name: 'Relay', exact: true }).check()
  await outgoing.getByRole('checkbox', { name: 'Spotlight 1', exact: true }).check()
  await outgoing.getByRole('checkbox', { name: 'Goal light', exact: true }).check()
  await selectBuilderObject(page, 'light:0')
  await expect(incoming.getByRole('checkbox')).toHaveCount(2)
  await expect(incoming.getByRole('checkbox', { name: 'Elevator 1 · Relay', exact: true })).toBeChecked()
  await behavior.getByRole('checkbox', { name: 'Relay', exact: true }).check()
  await outgoing.getByRole('checkbox', { name: 'Elevator 1', exact: true }).check()
  await expect(page.getByRole('complementary', { name: 'Inspector' })).toContainText('Relay wiring loop:')
  await expect(page.getByRole('button', { name: 'Save and Test', exact: true })).toBeDisabled()
  await outgoing.getByRole('checkbox', { name: 'Elevator 1', exact: true }).uncheck()
  await expect(page.getByRole('complementary', { name: 'Inspector' }).getByRole('alert')).toHaveCount(0)
  await outgoing.getByRole('checkbox', { name: 'Gate 3', exact: true }).check()
  await behavior.getByRole('checkbox', { name: 'Relay', exact: true }).uncheck()
  await expect(outgoing).toHaveCount(0)
  await selectBuilderObject(page, 'mechanism:2')
  await expect(incoming.getByRole('checkbox', { name: 'Spotlight 1 · Relay', exact: true })).toHaveCount(0)
  await selectBuilderObject(page, 'trigger:0')
  await selectBuilderOption(page, 'Pressure plate mount', 'platform')
  const saved = await saveTestLevel(page)
  expect(saved.level.mechanisms.map(m => m.switchLogic)).toEqual(['and', 'xor', undefined])
  expect(saved.level.mechanisms.every(m => m.switchReversed)).toBe(true)
  expect(saved.level.mechanisms[0]).toMatchObject({ relay: true, targets: ['lamp', 'exit'] })
  expect(saved.level.lighting.lights[0]).toMatchObject({ switchLogic: 'xor', switchReversed: true, relay: false })
  expect(saved.level.lighting.lights[0].targets).toBeUndefined()
  expect(saved.level.triggers[0].mount).toEqual({ mechanism: 'platform', x: 0 })
  await page.reload(); await reopenTestLevel(page, saved)
  for (const [object, logic] of objects) {
    await selectBuilderObject(page, object)
    await expect(page.getByRole('combobox', { name: 'Switch logic', exact: true })).toHaveText(logic.toUpperCase())
    await expect(behavior.getByRole('checkbox', { name: 'Reversed', exact: true })).toBeChecked()
  }
  await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('combobox', { name: 'Pressure plate mount' })).toHaveText('Moving platform 2')
  await selectBuilderObject(page, 'mechanism:0')
  await expect(behavior.getByRole('checkbox', { name: 'Relay', exact: true })).toBeChecked()
  await behavior.scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('relay-inspector.png') })
})

test('plate modes, exit wiring and always-on mechanisms save, undo and reopen in the studio', async ({ page }, info) => {
  const level = readLevelAsset('switch-modes.json')
  await useLevelFixtures(page, [level]); await installTestFolder(page, { 'switches.json': level })
  await page.goto('/untitled-jumping-game')
  await page.getByRole('button', { name: 'Level studio', exact: true }).click()
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  const local = page.getByRole('dialog').getByRole('button', { name: 'Local folder', exact: true })
  if (await local.count()) await local.click()
  await page.getByRole('button', { name: 'Choose folder', exact: true }).click()
  await page.getByRole('button', { name: 'Open switches.json', exact: true }).click()
  await expect(page.getByRole('application', { name: 'Level canvas' })).toHaveAttribute('aria-busy', 'false')
  await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('combobox', { name: 'Pressure plate mode' })).toHaveText('Pressure')
  await selectBuilderOption(page, 'Pressure plate mode', 'toggle')
  await expect(page.getByRole('combobox', { name: 'Pressure plate initial state' })).toHaveText('Off')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('combobox', { name: 'Pressure plate mode' })).toHaveText('Pressure')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await selectBuilderObject(page, 'trigger:0')
  await selectBuilderOption(page, 'Pressure plate initial state', 'on')
  await selectBuilderObject(page, 'mechanism:0'); await selectBuilderOption(page, 'Mechanism power', 'always')
  await selectBuilderObject(page, 'mechanism:1'); await selectBuilderOption(page, 'Mechanism power', 'always')
  await selectBuilderObject(page, 'mechanism:2')
  await expect(page.getByRole('combobox', { name: 'Mechanism power' })).toHaveCount(0)
  await selectBuilderObject(page, 'goal:0'); await selectBuilderOption(page, 'Exit power', 'always')
  await expect(page.getByRole('group', { name: 'Switched by' })).toHaveCount(0)
  await selectBuilderOption(page, 'Exit power', 'switched')
  const plate = page.getByRole('group', { name: 'Switched by' }).getByRole('checkbox', { name: 'Pressure plate 1' })
  await expect(plate).not.toBeChecked(); await plate.check()
  await selectBuilderObject(page, 'trigger:0')
  const activates = page.getByRole('group', { name: 'Activates' })
  await expect(activates.getByRole('checkbox', { name: 'Goal light' })).toBeChecked()
  await expect(activates.getByRole('checkbox', { name: 'Elevator 1' })).toHaveCount(0)
  await expect(activates.getByRole('checkbox', { name: 'Moving platform 2' })).toHaveCount(0)
  await activates.getByRole('checkbox', { name: 'Gate 3' }).check()
  await page.screenshot({ path: info.outputPath('toggle-inspector.png') })
  const saved = await saveTestLevel(page)
  expect(saved.level.triggers[0]).toMatchObject({ behavior: 'toggle', startsOn: true })
  expect(saved.level.triggers[0].targets).toEqual(['lamp', 'exit', 'gate'])
  expect(saved.level.mechanisms.slice(0, 2).map(m => m.power)).toEqual(['always', 'always'])
  expect(saved.level.goal).toMatchObject({ power: 'switched', id: 'exit' })
  await page.reload()
  await expect(page.getByRole('application', { name: 'Level canvas' })).toHaveAttribute('aria-busy', 'false')
  await reopenTestLevel(page, saved); await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('combobox', { name: 'Pressure plate mode' })).toHaveText('Toggle')
  await expect(page.getByRole('combobox', { name: 'Pressure plate initial state' })).toHaveText('On')
  await selectBuilderOption(page, 'Pressure plate mode', 'switch')
  await expect(page.getByRole('combobox', { name: 'Pressure plate initial state' })).toHaveText('Off')
  await selectBuilderOption(page, 'Pressure plate initial state', 'on')
  await expect(page.getByRole('complementary', { name: 'Inspector' })).toContainText('The first press switches off until restart.')
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('combobox', { name: 'Pressure plate initial state' })).toHaveText('Off')
  await page.getByRole('button', { name: 'Redo', exact: true }).click(); await selectBuilderObject(page, 'trigger:0')
  const switched = await saveTestLevel(page)
  expect(switched.level.triggers[0]).toMatchObject({ behavior: 'switch', startsOn: true })
  await page.reload(); await reopenTestLevel(page, switched); await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('combobox', { name: 'Pressure plate mode' })).toHaveText('Switch')
  await expect(page.getByRole('combobox', { name: 'Pressure plate initial state' })).toHaveText('On')
  await selectBuilderOption(page, 'Pressure plate mode', 'pressure')
  await expect(page.getByRole('combobox', { name: 'Pressure plate initial state' })).toHaveCount(0)
  const pressure = await saveTestLevel(page)
  expect(pressure.level.triggers[0].startsOn).toBeUndefined()
})
