import { readFileSync } from 'node:fs'
import { test, expect } from './helpers/test.mjs'
import { useLevelFixtures } from './helpers/jumpingLevels.mjs'

const level = JSON.parse(readFileSync(new URL('../fixtures/jumping/water-tunnel.json', import.meta.url), 'utf8'))
test('a held keyboard jump pushes from the pool bottom and settles against water resistance', async ({ page }, info) => {
  await useLevelFixtures(page, [level])
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') })
  await page.goto('/untitled-jumping-game?motionDebug=1')
  await expect(page.locator('.jumping-level-card[aria-pressed=true]')).toBeVisible()
  await page.clock.pauseAt(new Date('2026-01-01T01:00:00Z'))
  await page.locator('.jumping-level-card[aria-pressed=true]').click()
  const sample = () => page.evaluate(() => window.jumpingMotion.read().recent.at(-1))
  await page.clock.runFor(500)
  const bottom = await sample()
  expect(bottom.signals.grounded).toBe(true)
  await page.keyboard.down('Space')
  await page.clock.runFor(50)
  const push = await sample()
  expect(push.signals.grounded).toBe(false)
  expect(push.vy).toBeLessThan(-300)
  await page.clock.runFor(250)
  await page.keyboard.up('Space')
  const released = await sample()
  await page.clock.runFor(700)
  const slowing = await sample()
  expect(Math.abs(slowing.vy)).toBeLessThan(40)
  await page.clock.runFor(1800)
  const resting = await sample()
  expect(Math.abs(resting.vy)).toBeLessThan(.1)
  expect(bottom.waterCenter - resting.waterCenter).toBeGreaterThan(150)
  expect(bottom.waterCenter - resting.waterCenter).toBeLessThan(250)
  await page.clock.runFor(1000)
  const heldDepth = await sample()
  expect(Math.abs(resting.waterCenter - heldDepth.waterCenter)).toBeLessThan(.03)
  await page.screenshot({ path: info.outputPath('bottom-jump-settled.png') })
  await info.attach('bottom-push-off', { body: JSON.stringify({ bottom, push, released, slowing, resting, heldDepth }, null, 2), contentType: 'application/json' })
})
