import { test, expect } from './helpers/folderTest.mjs'
import { installTestFolder, useLevelFixtures, selectBuilderObject, saveTestLevel, reopenTestLevel } from './helpers/jumpingLevels.mjs'
import { blankTrial } from '../../src/games/jumping/level.ts'

async function open(page, level = blankTrial()) {
  await useLevelFixtures(page, [level]); await installTestFolder(page, { 'tabs.json': level })
  await page.addInitScript(() => {
    const fill = CanvasRenderingContext2D.prototype.fillRect
    CanvasRenderingContext2D.prototype.fillRect = function (...args) {
      if (this.fillStyle === '#f1f1ed' && args[0] === 0 && args[1] === 0) this.canvas.jumpCamera = this.getTransform()
      return fill.apply(this, args)
    }
  })
  await page.goto('/untitled-jumping-game')
  await page.getByRole('button', { name: 'Level studio', exact: true }).click()
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  const local = page.getByRole('dialog').getByRole('button', { name: 'Local folder', exact: true })
  if (await local.count()) await local.click()
  await page.getByRole('button', { name: 'Choose folder', exact: true }).click()
  await page.getByRole('button', { name: 'Open tabs.json', exact: true }).click()
  await expect(page.getByRole('application', { name: 'Level canvas' })).toHaveAttribute('aria-busy', 'false')
}

test('inspector tabs preserve edits and selection, support keyboard navigation, and follow canvas selection', async ({ page }, info) => {
  await open(page)
  const levelTab = page.getByRole('tab', { name: 'Level', exact: true })
  const objectTab = page.getByRole('tab', { name: 'Object', exact: true })
  const levelPanel = page.getByRole('tabpanel', { name: 'Level', exact: true })
  const objectPanel = page.getByRole('tabpanel', { name: 'Object', exact: true })
  const name = page.getByRole('textbox', { name: 'Level name', exact: true })
  const selected = page.getByRole('combobox', { name: 'Selected object' })
  await expect(levelTab).toHaveAttribute('aria-selected', 'true')
  await expect(levelPanel).toBeVisible(); await expect(objectPanel).toBeHidden()
  await name.fill('Tab workshop')
  await page.getByRole('checkbox', { name: 'Night mode', exact: true }).check()
  // Switching tabs is presentation only, and preserves level and object edits.
  await selectBuilderObject(page, 'spawn:0')
  await page.getByRole('textbox', { name: 'Object name', exact: true }).fill('Entry')
  await levelTab.click()
  await expect(name).toHaveValue('Tab workshop')
  await expect(page.getByRole('checkbox', { name: 'Night mode', exact: true })).toBeChecked()
  await page.screenshot({ path: info.outputPath('inspector-level.png') })
  await levelTab.focus(); await page.keyboard.press('ArrowRight')
  await expect(objectTab).toBeFocused(); await expect(objectTab).toHaveAttribute('aria-selected', 'true')
  await expect(selected).toHaveAttribute('data-value', 'spawn:0')
  await expect(page.getByRole('textbox', { name: 'Object name', exact: true })).toHaveValue('Entry')
  await page.keyboard.press('Tab'); await expect(selected).toBeFocused()
  await objectTab.focus(); await page.keyboard.press('Home')
  await expect(levelTab).toBeFocused(); await expect(levelPanel).toBeVisible()
  await page.keyboard.press('Tab'); await expect(name).toBeFocused()
  await levelTab.focus(); await page.keyboard.press('End')
  await expect(objectTab).toBeFocused()
  await page.keyboard.press('ArrowRight'); await expect(levelTab).toBeFocused()
  await page.keyboard.press('ArrowLeft'); await expect(objectTab).toBeFocused()
  const saved = await saveTestLevel(page)
  expect(saved.level.name).toBe('Tab workshop'); expect(saved.level.spawn.name).toBe('Entry')
  expect(saved.level.lighting.nightMode).toBe(true)
  await reopenTestLevel(page, saved)
  await expect(levelTab).toHaveAttribute('aria-selected', 'true')
  // Placing an object from Level opens Object without a separate tab click.
  await page.getByRole('button', { name: 'Box', exact: true }).click()
  const canvas = page.getByRole('application', { name: 'Level canvas' })
  await canvas.click({ position: { x: 180, y: 240 } })
  await expect(objectTab).toHaveAttribute('aria-selected', 'true')
  await expect(selected).toHaveAttribute('data-value', 'prop:0')
  await page.screenshot({ path: info.outputPath('inspector-object.png') })
  const { level: placed } = await saveTestLevel(page), box = placed.props[0]
  const center = await canvas.evaluate((c, box) => {
    const t = c.jumpCamera, ratio = c.width / c.getBoundingClientRect().width
    return { x: (box.x * t.a + t.e) / ratio, y: ((box.y - box.size / 2) * t.d + t.f) / ratio }
  }, box)
  await levelTab.click(); await canvas.click({ position: center })
  await expect(objectTab).toHaveAttribute('aria-selected', 'true')
  await expect(selected).toHaveAttribute('data-value', 'prop:0')
  await page.getByRole('button', { name: 'Delete object', exact: true }).click()
  await expect(objectTab).toHaveAttribute('aria-selected', 'true')
  await expect(objectPanel).toContainText('Select an object on the canvas to edit it.')
  await expect(selected).toHaveAttribute('data-value', '')
})

test('inspector tabs stay reachable while scrolling on a narrow screen', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await open(page)
  const inspector = page.getByRole('complementary', { name: 'Inspector', exact: true })
  const levelTab = page.getByRole('tab', { name: 'Level', exact: true })
  const objectTab = page.getByRole('tab', { name: 'Object', exact: true })
  await inspector.evaluate(el => { el.scrollTop = el.scrollHeight })
  for (const tab of [levelTab, objectTab]) await expect(tab).toBeInViewport()
  await expect(page.getByRole('spinbutton', { name: 'bronze time', exact: true })).toBeInViewport()
  await objectTab.click()
  await expect(page.getByRole('combobox', { name: 'Selected object' })).toBeInViewport()
  await selectBuilderObject(page, 'spawn:0')
  await inspector.evaluate(el => { el.scrollTop = el.scrollHeight })
  await levelTab.click()
  await expect(page.getByRole('textbox', { name: 'Level name', exact: true })).toBeInViewport()
  expect(await inspector.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('inspector-tabs-narrow.png') })
})


test('styled object picker supports type-ahead, keyboard commit, cancellation and long lists without editing the canvas', async ({ page }, info) => {
  const level = blankTrial()
  level.props = Array.from({ length: 28 }, (_, i) => ({ kind: 'box', x: 300 + i * 40, y: 920, size: 40, name: `Crate ${String(i + 1).padStart(2, '0')}` }))
  await open(page, level)
  await page.getByRole('tab', { name: 'Object', exact: true }).click()
  const picker = page.getByRole('combobox', { name: 'Selected object' })
  const menu = page.getByRole('listbox', { name: 'Selected object' })
  const active = async () => page.locator(`[id=${JSON.stringify(await picker.getAttribute('aria-activedescendant'))}]`)
  await picker.focus(); await picker.press('Enter')
  await expect(menu).toBeVisible(); await expect(picker).toBeFocused()
  await expect(menu.getByRole('option')).toHaveCount(31)
  await picker.press('End'); await expect(await active()).toHaveText('Crate 28 · Box 28')
  await expect(await active()).toBeInViewport()
  await picker.press('Escape'); await expect(menu).toBeHidden()
  await expect(picker).toHaveAttribute('data-value', '')
  await picker.press('g'); await expect(await active()).toHaveText('Goal light')
  await picker.press('Enter'); await expect(picker).toHaveText('Goal light')
  await expect(picker).toHaveAttribute('data-value', 'goal:0')
  await picker.press('n'); await expect(await active()).toHaveText('Nothing selected')
  await expect(page.getByRole('button', { name: 'Node', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await picker.press('Escape'); await expect(picker).toHaveText('Goal light')
  await picker.press('Home'); await picker.press('ArrowDown'); await picker.press('Tab')
  await expect(picker).toHaveAttribute('data-value', 'spawn:0')
  await expect(page.getByRole('textbox', { name: 'Object name', exact: true })).toBeFocused()
  await picker.click(); await menu.getByRole('option', { name: 'Crate 04 · Box 4', exact: true }).click()
  await expect(picker).toHaveText('Crate 04 · Box 4'); await expect(picker).toBeFocused()
  await expect(page.getByRole('status', { name: 'Builder status' })).toContainText('Saved to folder')
  await picker.click(); await page.screenshot({ path: info.outputPath('styled-object-picker.png') })
  await page.getByRole('tab', { name: 'Level', exact: true }).click()
  await expect(menu).toBeHidden()
  await page.getByRole('tab', { name: 'Object', exact: true }).click()
  await expect(picker).toHaveText('Crate 04 · Box 4')
  await page.setViewportSize({ width: 1280, height: 650 })
  await picker.click()
  await page.getByRole('complementary', { name: 'Inspector' }).evaluate(el => { el.scrollTop = el.scrollHeight })
  await expect(menu).toBeHidden()
})

test('styled picker opens above a narrow inspector and remains usable with forced colors', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 }); await open(page)
  await page.getByRole('tab', { name: 'Object', exact: true }).click()
  const picker = page.getByRole('combobox', { name: 'Selected object' })
  await picker.click()
  const menu = page.getByRole('listbox', { name: 'Selected object' })
  const control = await picker.boundingBox(), popup = await menu.boundingBox()
  expect(popup.y + popup.height).toBeLessThanOrEqual(control.y)
  for (const option of await menu.getByRole('option').all()) await expect(option).toBeInViewport()
  await page.screenshot({ path: info.outputPath('styled-picker-narrow.png') })
  await menu.getByRole('option', { name: 'Start', exact: true }).click()
  await expect(picker).toHaveText('Start')
  await page.emulateMedia({ forcedColors: 'active' })
  await picker.press('Enter'); await picker.press('End')
  await expect(menu.getByRole('option', { name: 'Goal light', exact: true })).toHaveAttribute('data-active', 'true')
  await page.screenshot({ path: info.outputPath('styled-picker-forced-colors.png') })
  await picker.press('Escape'); await expect(picker).toHaveText('Start')
})
