import { test, expect } from './helpers/folderTest.mjs'
import { installTestFolder, useLevelFixtures, readTestLevel } from './helpers/jumpingLevels.mjs'
import { hold, tap } from './helpers/controller.mjs'
import { blankTrial } from '../../src/games/jumping/level.ts'

const canvas = page => page.getByRole('application', { name: 'Level canvas' })
const field = (page, name) => page.getByRole('spinbutton', { name, exact: true })
async function open(page) {
  const level = blankTrial()
  await useLevelFixtures(page, [level])
  await installTestFolder(page, { 'controller.json': level })
  await page.addInitScript(() => {
    window.testPad = { index: 1, id: 'Studio controller', connected: true, mapping: 'standard', axes: [0, 0, 0, 0],
      buttons: Array.from({ length: 17 }, () => ({ pressed: false, value: 0 })) }
    Object.defineProperty(navigator, 'getGamepads', { configurable: true, value: () => [null, window.testPad] })
  })
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') })
  await page.goto('/untitled-jumping-game')
  await page.getByRole('button', { name: 'Level studio', exact: true }).click()
  await page.clock.pauseAt(new Date('2026-01-01T01:00:00Z'))
  await page.clock.runFor(64)
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'Choose folder', exact: true }).click()
  await page.getByRole('button', { name: 'Open controller.json', exact: true }).click()
  await page.clock.runFor(200)
  await expect(canvas(page)).toHaveAttribute('aria-busy', 'false')
  await page.clock.runFor(64)
}
async function focus(page, target) { await target.focus(); await page.clock.runFor(64) }
async function activate(page, target) { await focus(page, target); await tap(page, 0) }
async function axes(page, values, ms = 160) {
  await page.evaluate(values => { window.testPad.axes = values }, values)
  await page.clock.runFor(ms)
}
async function placeBox(page) {
  await activate(page, page.getByRole('button', { name: 'Box', exact: true }))
  await tap(page, 3)
  await expect(canvas(page)).toBeFocused()
  // Draw a free-standing box; a click deliberately places props on the floor.
  await hold(page, 10, 1); await hold(page, 0, 1)
  await axes(page, [1, 1, 0, 0], 320); await axes(page, [0, 0, 0, 0])
  await hold(page, 0, 0); await hold(page, 10, 0)
  await expect(field(page, 'Object x')).toBeVisible()
}

test('controller navigates controls, number fields, lists, Help and Library', async ({ page }, info) => {
  await open(page)
  const snap = page.getByRole('checkbox', { name: 'Snap', exact: true })
  await activate(page, snap)
  await expect(snap).not.toBeChecked()
  await tap(page, 15)
  await expect(page.getByRole('checkbox', { name: 'Keep placing', exact: true })).toBeFocused()
  const width = field(page, 'Level width'), initial = Number(await width.inputValue())
  await focus(page, width); await tap(page, 15)
  await expect(width).toHaveValue(String(initial + 100))
  await hold(page, 10, 1); await tap(page, 14); await hold(page, 10, 0)
  await expect(width).toHaveValue(String(initial + 99))
  await activate(page, page.getByRole('tab', { name: 'Object', exact: true }))
  const selected = page.getByRole('combobox', { name: 'Selected object', exact: true })
  await focus(page, selected); await hold(page, 0, 1, 400)
  await expect(selected).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByRole('listbox', { name: 'Selected object', exact: true })).toBeVisible()
  await hold(page, 0, 0); await tap(page, 13); await tap(page, 0)
  await expect(selected).toHaveAttribute('aria-expanded', 'false')
  await expect(field(page, 'Object x')).toBeVisible()
  await activate(page, page.getByRole('button', { name: 'Help', exact: true }))
  const help = page.getByRole('dialog', { name: 'Level builder help', exact: true })
  await expect(help).toBeVisible()
  await help.getByRole('tab', { name: 'Canvas', exact: true }).focus()
  await tap(page, 14)
  await expect(help.getByRole('tab', { name: 'Controller', exact: true })).toBeFocused()
  await expect(help.getByRole('tabpanel', { name: 'Controller', exact: true })).toContainText('Left-stick click')
  await help.getByRole('tabpanel', { name: 'Controller', exact: true }).focus()
  await axes(page, [0, 0, 0, 1], 500)
  expect(await help.getByRole('tabpanel', { name: 'Controller', exact: true }).evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  await axes(page, [0, 0, 0, 0])
  await page.screenshot({ path: info.outputPath('controller-help.png') })
  await tap(page, 1)
  await expect(help).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Help', exact: true })).toBeFocused()
  await tap(page, 8)
  await expect(page.getByRole('dialog', { name: 'Level library', exact: true })).toBeVisible()
  await tap(page, 1)
  await expect(page.getByRole('dialog', { name: 'Level library', exact: true })).toHaveCount(0)
})

test('controller places, drags, nudges, duplicates, pans, zooms and saves a playable draft', async ({ page }, info) => {
  await open(page)
  await placeBox(page)
  const x = field(page, 'Object x'), y = field(page, 'Object y'), initial = Number(await x.inputValue())
  // The drawn object's lower-right corner is under the cursor: move inward.
  await hold(page, 10, 1)
  await axes(page, [-1, -1, 0, 0], 160); await axes(page, [0, 0, 0, 0]); await hold(page, 10, 0)
  await hold(page, 0, 1)
  await axes(page, [1, 0, 0, 0], 320); await axes(page, [0, 0, 0, 0]); await hold(page, 0, 0)
  const dragged = Number(await x.inputValue())
  expect(dragged).toBeGreaterThan(initial)
  const afterY = await y.inputValue()
  await tap(page, 15)
  await expect(x).toHaveValue(String(dragged + 20))
  await tap(page, 4)
  // Undo/redo clears selection; reselect with the inspector to inspect the edit.
  await activate(page, page.getByRole('combobox', { name: 'Selected object', exact: true }))
  await tap(page, 13); await tap(page, 13); await tap(page, 13); await tap(page, 0)
  await expect(x).toHaveValue(String(dragged))
  await tap(page, 5)
  await activate(page, page.getByRole('combobox', { name: 'Selected object', exact: true }))
  await tap(page, 13); await tap(page, 13); await tap(page, 13); await tap(page, 0)
  await expect(x).toHaveValue(String(dragged + 20))
  await tap(page, 3); await tap(page, 2)
  const zoom = await page.getByRole('status', { name: 'Zoom', exact: true }).textContent()
  await hold(page, 7, .8, 250); await hold(page, 7, 0)
  expect(await page.getByRole('status', { name: 'Zoom', exact: true }).textContent()).not.toBe(zoom)
  const before = await page.getByRole('status', { name: 'Cursor coordinates', exact: true }).textContent()
  await axes(page, [0, 0, 1, 0], 250); await axes(page, [0, 0, 0, 0])
  expect(await page.getByRole('status', { name: 'Cursor coordinates', exact: true }).textContent()).not.toBe(before)
  await page.screenshot({ path: info.outputPath('controller-canvas.png') })
  await tap(page, 9)
  await expect(page.getByRole('button', { name: 'Return to builder', exact: true })).toBeVisible()
  const saved = await readTestLevel(page, 'controller.json')
  expect(saved.props).toHaveLength(2)
  expect(saved.props[0].x - saved.props[0].size / 2).toBeCloseTo(dragged + 20)
  expect(saved.height - saved.props[0].y + saved.props[0].size).toBeCloseTo(Number(afterY))
  await page.clock.runFor(200)
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toHaveCount(0)
})

test('disconnect, cancellation and mouse handoff preserve committed geometry', async ({ page }) => {
  await open(page); await placeBox(page)
  const x = field(page, 'Object x'), initial = await x.inputValue()
  await hold(page, 10, 1); await axes(page, [-1, -1, 0, 0], 160); await axes(page, [0, 0, 0, 0]); await hold(page, 10, 0)
  const body = await page.locator('.builder-controller-cursor').boundingBox()
  await hold(page, 0, 1); await axes(page, [1, 0, 0, 0], 250)
  expect(await x.inputValue()).not.toBe(initial)
  await page.evaluate(() => { window.testPad.connected = false }); await page.clock.runFor(64)
  await expect(x).toHaveValue(initial)
  await page.evaluate(() => { window.testPad.connected = true }); await page.clock.runFor(250)
  await expect(x).toHaveValue(initial)
  await axes(page, [0, 0, 0, 0]); await hold(page, 0, 0)
  // Return the cursor to the body, then cancel without adding a history entry.
  await axes(page, [-1, 0, 0, 0], 250); await axes(page, [0, 0, 0, 0])
  await hold(page, 0, 1); await axes(page, [1, 0, 0, 0], 150)
  expect(await x.inputValue()).not.toBe(initial)
  await axes(page, [0, 0, 0, 0])
  await tap(page, 1)
  await expect(x).toHaveValue(initial)
  await hold(page, 0, 0); await axes(page, [0, 0, 0, 0])
  await axes(page, [-1, 0, 0, 0], 150); await axes(page, [0, 0, 0, 0])
  await hold(page, 0, 1); await axes(page, [1, 0, 0, 0], 150)
  expect(await x.inputValue()).not.toBe(initial)
  await page.evaluate(() => window.dispatchEvent(new Event('blur'))); await page.clock.runFor(64)
  await expect(x).toHaveValue(initial)
  await axes(page, [0, 0, 0, 0]); await hold(page, 0, 0)
  // An idle controller must leave a physical mouse drag alone.
  await page.mouse.move(body.x + body.width / 2, body.y + body.height / 2)
  await page.mouse.down(); await page.mouse.move(body.x + body.width / 2 + 64, body.y + body.height / 2, { steps: 5 })
  await page.clock.runFor(250); await page.mouse.up()
  expect(await x.inputValue()).not.toBe(initial)
  await tap(page, 4)
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeEnabled()
  await tap(page, 4)
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
})

test('testing during a controller drag cancels its preview before saving', async ({ page }) => {
  await open(page); await placeBox(page)
  const x = field(page, 'Object x'), initial = Number(await x.inputValue())
  await hold(page, 10, 1); await axes(page, [-1, -1, 0, 0], 160); await axes(page, [0, 0, 0, 0]); await hold(page, 10, 0)
  await hold(page, 0, 1); await axes(page, [1, 0, 0, 0], 150)
  expect(Number(await x.inputValue())).toBeGreaterThan(initial)
  await tap(page, 9)
  await expect(x).toHaveValue(String(initial))
  await expect(page.getByRole('button', { name: 'Return to builder', exact: true })).toHaveCount(0)
  await axes(page, [0, 0, 0, 0]); await hold(page, 0, 0)
  await tap(page, 9)
  await expect(page.getByRole('button', { name: 'Return to builder', exact: true })).toBeVisible()
  const saved = await readTestLevel(page, 'controller.json')
  expect(saved.props).toHaveLength(1)
  expect(saved.props[0].x - saved.props[0].size / 2).toBeCloseTo(initial)
})

test('account dialogs own controller input and editor shortcuts rearm after closing', async ({ page }) => {
  await open(page)
  await activate(page, page.getByRole('button', { name: 'Sign in', exact: true }))
  const account = page.getByRole('dialog', { name: 'Player account', exact: true })
  await expect(account).toBeVisible()
  await hold(page, 9, 1); await tap(page, 8); await tap(page, 3)
  await expect(account).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Level library', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Return to builder', exact: true })).toHaveCount(0)
  await tap(page, 1); await page.clock.runFor(200)
  await expect(account).toHaveCount(0)
  // Menu was held while the global dialog closed: it must not start testing.
  await expect(page.getByRole('button', { name: 'Return to builder', exact: true })).toHaveCount(0)
  await hold(page, 9, 0)
  await tap(page, 8)
  await expect(page.getByRole('dialog', { name: 'Level library', exact: true })).toBeVisible()
  await tap(page, 1)
  await expect(page.getByRole('dialog', { name: 'Level library', exact: true })).toHaveCount(0)
})

test('controller text entry applies and cancels names, including at narrow widths', async ({ page }, info) => {
  await open(page)
  const name = page.getByRole('textbox', { name: 'Level name', exact: true }), initial = await name.inputValue()
  await focus(page, name); await hold(page, 0, 1, 300)
  const keyboard = page.getByRole('dialog', { name: 'Edit Level name', exact: true })
  await expect(keyboard).toBeVisible()
  await expect(keyboard.getByRole('status', { name: 'Text entry preview', exact: true })).toHaveText(initial)
  await hold(page, 0, 0)
  await activate(page, keyboard.getByRole('button', { name: 'Clear', exact: true }))
  await activate(page, keyboard.getByRole('button', { name: 'Type a', exact: true }))
  await tap(page, 15); await tap(page, 0) // Adjacent key: s.
  await expect(keyboard.getByRole('status', { name: 'Text entry preview', exact: true })).toHaveText('as')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await keyboard.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('controller-text-narrow.png') })
  await activate(page, keyboard.getByRole('button', { name: 'Done', exact: true }))
  await expect(keyboard).toHaveCount(0); await expect(name).toHaveValue('as')
  await tap(page, 0)
  await activate(page, keyboard.getByRole('button', { name: 'Clear', exact: true }))
  await tap(page, 1)
  await expect(keyboard).toHaveCount(0); await expect(name).toHaveValue('as')
  await page.setViewportSize({ width: 1280, height: 800 })
  await placeBox(page)
  const objectName = page.getByRole('textbox', { name: 'Object name', exact: true })
  await activate(page, objectName)
  const objectKeyboard = page.getByRole('dialog', { name: 'Edit Object name', exact: true })
  await activate(page, objectKeyboard.getByRole('button', { name: 'Type b', exact: true }))
  await activate(page, objectKeyboard.getByRole('button', { name: 'Done', exact: true }))
  await expect(objectName).toHaveValue('b')
  await activate(page, page.getByRole('button', { name: 'Save level', exact: true }))
  await expect(page.getByRole('status', { name: 'Builder status' })).toContainText('Saved')
  const saved = await readTestLevel(page, 'controller.json')
  expect(saved.name).toBe('as'); expect(saved.props[0].name).toBe('b')
})
