import { test, expect } from './helpers/test.mjs'
import { useLevelFixtures } from './helpers/jumpingLevels.mjs'
import { FIRST_LEVEL } from '../helpers/jumping-fixtures.mjs'

async function play(page, lighting = false) {
  const level = structuredClone(FIRST_LEVEL)
  if (lighting) {
    level.version = 2
    level.lighting = { nightMode: lighting !== 'day', ambient: 25, lights: [] }
  }
  await useLevelFixtures(page, [level])
  await page.goto('/untitled-jumping-game')
  await page.getByRole('button', { name: `Play ${level.name}`, exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
}

test('performance monitor is opt-in, keeps gameplay focus, freezes on pause and persists its toggle', async ({ page }) => {
  await play(page)
  const panel = page.getByRole('complementary', { name: 'Performance monitor' })
  const developer = page.getByRole('dialog', { name: 'Developer panel' })
  const toggle = page.getByRole('switch', { name: 'Performance monitor', exact: true })
  await expect(panel).toHaveCount(0)
  await page.keyboard.press('Backquote')
  await expect(developer).toBeVisible()
  await expect(toggle).toBeFocused()
  await expect(toggle).not.toBeChecked()
  await toggle.click()
  await page.keyboard.press('Backquote')
  await expect(developer).toHaveCount(0)
  await expect(panel).toContainText('FPS')
  await expect(page.locator('.jumping-game > canvas')).toBeFocused()
  await expect(panel).toContainText('Canvas')
  await page.keyboard.press('Escape')
  await expect(toggle).toHaveCount(0)
  await page.keyboard.press('Backquote')
  await expect(toggle).toBeChecked()
  await expect(panel).toContainText('Paused · last sample')
  await page.clock.install()
  const frozen = await panel.innerText()
  await page.clock.runFor(5000)
  expect(await panel.innerText()).toBe(frozen)
  await page.keyboard.press('Escape')
  await expect(developer).toHaveCount(0)
  await expect(page.getByRole('dialog', { name: 'Game paused' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Resume', exact: false })).toBeFocused()
  await page.getByRole('button', { name: 'Resume', exact: false }).click()
  await page.clock.runFor(600)
  await expect(panel).not.toContainText('Paused')
  const worst = panel.locator('dl > div').filter({ has: page.getByText('Worst frame', { exact: true }) }).locator('dd')
  expect(parseFloat(await worst.innerText())).toBeLessThan(100)
  await page.reload()
  await expect(panel).toBeVisible()
  await page.keyboard.press('Backquote')
  await toggle.click()
  await expect(toggle).not.toBeChecked()
  await expect(panel).toHaveCount(0)
  await developer.getByRole('button', { name: /^Close/ }).click()
  await expect(page.locator('.jumping-game > canvas')).toBeFocused()
  await expect(panel).toHaveCount(0)
})

test('shows actual lighting resolution and fits a narrow viewport', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await play(page, true)
  await page.keyboard.press('Backquote')
  const developer = page.getByRole('dialog', { name: 'Developer panel' })
  await expect(developer).toBeVisible()
  const devBounds = await developer.locator('.jumping-development').boundingBox()
  expect(devBounds.x).toBeGreaterThanOrEqual(0)
  expect(devBounds.x + devBounds.width).toBeLessThanOrEqual(390)
  expect(devBounds.y + devBounds.height).toBeLessThanOrEqual(844)
  await page.screenshot({ path: info.outputPath('developer-panel-mobile.png') })
  await page.keyboard.press('Enter')
  await page.keyboard.press('Escape')
  await expect(page.locator('.jumping-game > canvas')).toBeFocused()
  const panel = page.getByRole('complementary', { name: 'Performance monitor' })
  await expect(panel).toContainText('FPS')
  const pixels = await page.locator('.jumping-game > canvas').evaluate(canvas => `${canvas.width} × ${canvas.height}`)
  await expect(panel).toContainText(pixels)
  await expect(panel).toContainText('0 / 0')
  const bounds = await panel.boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390)
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(844)
  await page.screenshot({ path: info.outputPath('performance-monitor-mobile.png') })
  await page.keyboard.press('Backquote')
  await page.getByRole('switch', { name: 'Performance monitor', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(panel).toHaveCount(0)
})

for (const lighting of [true, 'day', false]) for (const savedPreference of [null, 'false', 'true']) test(`${lighting === true ? 'night' : lighting === 'day' ? 'day' : 'legacy day'} lighting performance preference ${savedPreference ?? 'default'} controls low-FPS reduction and switching off restores quality`, async ({ page }) => {
  // Exercise real resizing without rendering hundreds of 2 MP software frames.
  await page.setViewportSize({ width: 640, height: 360 })
  await page.addInitScript(value => {
    localStorage.setItem('jumping:performance-monitor', 'true')
    if (value !== null) localStorage.setItem('jumping:lighting-performance-mode', value)
    Object.defineProperty(window, 'devicePixelRatio', { configurable: true, value: 2 })
  }, savedPreference)
  await page.clock.install()
  await play(page, lighting)
  const fullPixels = await page.locator('.jumping-game > canvas').evaluate(canvas => canvas.width * canvas.height)
  await page.evaluate(() => {
    // Install after Playwright's clock, which also wraps animation callbacks.
    window.requestAnimationFrame = callback => window.setTimeout(() => callback(performance.now()), 100)
    window.cancelAnimationFrame = id => window.clearTimeout(id)
  })
  await page.clock.runFor(3000)
  const panel = page.getByRole('complementary', { name: 'Performance monitor' })
  const shadows = panel.locator('dl > div').filter({ has: page.getByText('Object shadows', { exact: true }) }).locator('dd')
  await expect(shadows).toHaveText('Off')
  await page.keyboard.press('Backquote')
  const mode = page.getByRole('switch', { name: 'Lighting performance mode', exact: true })
  if (savedPreference === 'false') {
    await expect(mode).not.toBeChecked()
    await mode.click()
  } else await expect(mode).toBeChecked()
  await page.keyboard.press('Backquote')
  await page.clock.runFor(2800)
  await expect(shadows).toHaveText('Off')
  const reducedPixels = await page.locator('.jumping-game > canvas').evaluate(canvas => canvas.width * canvas.height)
  expect(reducedPixels).toBeLessThan(fullPixels)
  expect(reducedPixels).toBeLessThan(1_005_000)
  await page.keyboard.press('Backquote')
  await expect(mode).toBeChecked()
  await expect(page.getByText(/Rendering resolution is reduced for this run/)).toBeVisible()
  await mode.click()
  await page.keyboard.press('Backquote')
  await page.clock.runFor(600)
  await expect(shadows).toHaveText('Off')
  expect(await page.locator('.jumping-game > canvas').evaluate(canvas => canvas.width * canvas.height)).toBe(fullPixels)
  expect(await page.evaluate(() => localStorage.getItem('jumping:lighting-performance-mode'))).toBe('false')
})
