import { test, expect } from './helpers/folderTest.mjs'
import { selectBuilderObject, selectBuilderOption, installTestFolder, useLevelFixtures, saveTestLevel, reopenTestLevel } from './helpers/jumpingLevels.mjs'
import { readLevelAsset } from '../helpers/jumping-fixtures.mjs'

test('plate modes, exit wiring and always-on mechanisms save, undo and reopen in the studio', async ({ page }, info) => {
  const level = readLevelAsset('switch-modes.json')
  await useLevelFixtures(page, [level]); await installTestFolder(page, { 'switches.json': level })
  await page.goto('/untitled-jumping-game')
  await page.getByRole('button', { name: 'Level studio', exact: true }).click()
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  const local = page.getByRole('dialog').getByRole('button', { name: 'Local folder', exact: true })
  if (await local.count()) await local.click()
  await page.getByRole('button', { name: 'Choose folder', exact: true }).click()
  await page.getByRole('button', { name: 'Open switches.json', exact: true }).click()
  await expect(page.getByRole('application', { name: 'Level canvas' })).toHaveAttribute('aria-busy', 'false')
  await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('combobox', { name: 'Pressure plate mode' })).toHaveText('Pressure')
  await selectBuilderOption(page, 'Pressure plate mode', 'toggle')
  await expect(page.getByRole('combobox', { name: 'Pressure plate initial state' })).toHaveText('Off')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('combobox', { name: 'Pressure plate mode' })).toHaveText('Pressure')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await selectBuilderObject(page, 'trigger:0')
  await selectBuilderOption(page, 'Pressure plate initial state', 'on')
  await selectBuilderObject(page, 'mechanism:0'); await selectBuilderOption(page, 'Mechanism power', 'always')
  await selectBuilderObject(page, 'mechanism:1'); await selectBuilderOption(page, 'Mechanism power', 'always')
  await selectBuilderObject(page, 'mechanism:2')
  await expect(page.getByRole('combobox', { name: 'Mechanism power' })).toHaveCount(0)
  await selectBuilderObject(page, 'goal:0'); await selectBuilderOption(page, 'Exit power', 'always')
  await expect(page.getByRole('group', { name: 'Switched by' })).toHaveCount(0)
  await selectBuilderOption(page, 'Exit power', 'switched')
  const plate = page.getByRole('group', { name: 'Switched by' }).getByRole('checkbox', { name: 'Pressure plate 1' })
  await expect(plate).not.toBeChecked(); await plate.check()
  await selectBuilderObject(page, 'trigger:0')
  const activates = page.getByRole('group', { name: 'Activates' })
  await expect(activates.getByRole('checkbox', { name: 'Goal light' })).toBeChecked()
  await expect(activates.getByRole('checkbox', { name: 'Elevator 1' })).toHaveCount(0)
  await expect(activates.getByRole('checkbox', { name: 'Moving platform 2' })).toHaveCount(0)
  await activates.getByRole('checkbox', { name: 'Gate 3' }).check()
  await page.screenshot({ path: info.outputPath('toggle-inspector.png') })
  const saved = await saveTestLevel(page)
  expect(saved.level.triggers[0]).toMatchObject({ behavior: 'toggle', startsOn: true })
  expect(saved.level.triggers[0].targets).toEqual(['lamp', 'exit', 'gate'])
  expect(saved.level.mechanisms.slice(0, 2).map(m => m.power)).toEqual(['always', 'always'])
  expect(saved.level.goal).toMatchObject({ power: 'switched', id: 'exit' })
  await page.reload()
  await expect(page.getByRole('application', { name: 'Level canvas' })).toHaveAttribute('aria-busy', 'false')
  await reopenTestLevel(page, saved); await selectBuilderObject(page, 'trigger:0')
  await expect(page.getByRole('combobox', { name: 'Pressure plate mode' })).toHaveText('Toggle')
  await expect(page.getByRole('combobox', { name: 'Pressure plate initial state' })).toHaveText('On')
  await selectBuilderOption(page, 'Pressure plate mode', 'switch')
  await expect(page.getByRole('combobox', { name: 'Pressure plate initial state' })).toHaveCount(0)
  const switched = await saveTestLevel(page)
  expect(switched.level.triggers[0].behavior).toBe('switch')
  expect(switched.level.triggers[0].startsOn).toBeUndefined()
})
