import { writeFile } from 'node:fs/promises'
import { routePowerConduits } from '../src/games/hardVacuum/powerWiring.ts'

const entries=routePowerConduits().map(({source,target,path})=>
  `  ${JSON.stringify(`${source}/${target}`)}: ${JSON.stringify(path.map(({x,y})=>[x,y]))},`)
await writeFile(new URL('../src/games/hardVacuum/powerPaths.ts',import.meta.url),
  '// Generated by npm run generate:power. Validated against the station router in tests.\n'+
  'export const POWER_PATHS: Record<string, readonly (readonly [number,number])[]> = {\n'+entries.join('\n')+'\n}\n')
console.log(`Authored ${entries.length} fixed power routes.`)
